# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4be56d95d4c4143cddf1c58418e18d5901e59dce66931d5014b81b7d3fc4053982e8c5270c920bd5c559365f5dcbe103f8118e89f52c79978b1eed7a8c09efc

test:
  secret_key_base: fff0119c7facfe8995dd331828b29e6466de633d1e1045f03fb8d04107d0960490d61754da8c6fee4183ce3414114c958a2ca9b37a5c027b0c4ee1674e7ed3ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
